In [40]:
import numpy as np

In [41]:
def f(x, y):
    return x*x + 3*x + 2*x*y + y + y*y + 1350

In [45]:
position = (1, 1)
a = np.fromfunction(f, (40, 40), dtype=int)
for x in np.nditer(a, op_flags=["readwrite"]):
    b = bin(x)
    if b.count('1') % 2 == 1:
        x[...] = 1
    else:
        x[...] = 0

In [46]:
print a

[[1 0 1 ..., 1 0 0]
 [1 0 1 ..., 1 1 0]
 [0 0 1 ..., 0 1 1]
 ..., 
 [0 1 0 ..., 1 0 1]
 [1 1 1 ..., 1 0 1]
 [1 1 0 ..., 0 0 0]]


[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]] [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [35]:
b = bin(s)
    print s, b
    if b.count('1') % 2 == 1:
        return 1
    else:
        return 0

1350 0b10101000110


1